### ISSUE TITLE
Error executing POST request 

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Speech-TTS#2]
_From @Juude on November 18, 2015 10:40_

give me the error
Error: Error executing POST request！
Received error code:401

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#4_

**Comment by margaretmz** [comment]
_From @yungshinlintw on November 20, 2015 23:37_

Hi Juude,

Thanks for the feedback. Can you please give more details about what API (face, speech, etc) that you are using, or what sample gave you the error? Given more details, we will look into it. Sorry for the inconvenience.

Thanks,
Yung-Shin

**Comment by margaretmz** [comment]
_From @dlfu on November 25, 2015 19:33_

hi @Juude ! 
is it possible that you did not provide the subscription key? usually 401 error is a permission issue

**Comment by margaretmz** [comment]
_From @yungshinlintw on November 25, 2015 19:43_

Please also note that subscription key is per service (face, speech, etc). Here is the updated page to get subscription key for free use: http://projectoxford.ai/subscription

**Comment by margaretmz** [comment]
_From @lightfrenzy on December 17, 2015 21:38_

Bump to @Juude, are you still having an issue with the API? Let us know so we can file a bug report or close out this issue.

Thanks!

**Comment by margaretmz** [comment]
_From @IgnacioHR on December 21, 2015 13:9_

Line 496 in code is misleading. It should read:
Authentication auth = new Authentication("Your ClientId goes here", "Your Primary Key for Speech API goes here");

**Comment by gcrev93** [comment]
For the TTS sdk, how do you actually get the wave file? it just gives you how big the file is.. but doesnt actually write the wav file?

**Comment by TroutNemesis** [comment]
I'd like to second what @gcrev93 said.  I'm working on TTS in PHP. How do you use the result variable or turn it into a wave file?

**Comment by cthrash** [comment]
What do you mean by 'turn in into a wave file'?  Do you want this file on the client or the server?  If you want something playable on a web page, for instance, you can do something like this:

```
<?php
        ...
        echo "<audio id=\"tts\"><source type=\"audio/wav\" src=\"data:audio/wav;base64," . base64_encode($result) . "\"></audio>";
    }
}
?>  
<button onclick="document.all['tts'].play()">Play</button>

```
