### ISSUE TITLE
Android SDK error Non-empty xml:lang attribute must be present

### ISSUE THREAD

**Issue by shaqian** [Microsoft/Cognitive-Speech-TTS#24]
Resolution: 
in [Synthesizer.java](https://github.com/Microsoft/Cognitive-Speech-TTS/blob/master/Android/Sample/speechsdk/src/main/java/com/microsoft/speech/tts/Synthesizer.java)
change
`String ssml = "<speak version='1.0' xml:lang='" + m_serviceVoice.lang + "'><voice xml:gender='" + m_serviceVoice.gender + "'";
`
to
`String ssml = "<speak version='1.0' xml:lang='" + m_serviceVoice.lang + "'><voice xml:lang='" + m_serviceVoice.lang + "' xml:gender='" + m_serviceVoice.gender + "'";`

[API Reference: ](https://www.microsoft.com/cognitive-services/en-us/Speech-api/documentation/API-Reference-REST/BingVoiceOutput)
`<speak version='1.0' xml:lang='en-US'><voice xml:lang='en-US' xml:gender='Female' name='Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)'>Microsoft Bing Voice Output API</voice></speak>`

**Comment by boltomli** [comment]
Thanks for the issue. Do you have a PR for the fix?
