### ISSUE TITLE
My project stop getting audios correctly

### ISSUE THREAD

**Issue by rodrigomocca** [Microsoft/Cognitive-Speech-TTS#30]
I have a asp mvc project using text to speech api. This project work for a year without problems.
A few days ago I've noticed that this project stop generating audios. I don't know when exactly this happened.
The api is returning wav audios that I can't play, the file throw an error when I try to play it.
Was there any significant change that I have to make in my project to get this working again?

**Comment by szhaomsft** [comment]
can u check our samples using your subscription? 

it may be due to some ssml format changes.

**Comment by priyaravi20** [comment]
Please check the encoders on your side. No recent changes have been made this repo and I was able to use the existing samples with no issues.
