### ISSUE TITLE
Connection cleanup in Authentication class of SpeechSDK

### ISSUE THREAD

**Issue by mridulasandy** [Microsoft/Cognitive-Speech-TTS#7]
The best practice is to have finally block to check status of the connection and close it.

`//webRequest.disconnect();

            this.accessToken = strBuffer.toString();

        }catch (Exception e){
            Log.e(LOG_TAG, "Exception error", e);
        }
        finally {
            if (webRequest != null) {
                webRequest.disconnect();
            }
        }`

**Comment by priyaravi20** [comment]
Thanks.
